//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>ActionBar</summary>
	[PublishedContentModel("actionBar")]
	public partial class ActionBar : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "actionBar";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ActionBar(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ActionBar, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// ActionBarHeadline1
		///</summary>
		[ImplementPropertyType("actionBarHeadline1")]
		public string ActionBarHeadline1
		{
			get { return this.GetPropertyValue<string>("actionBarHeadline1"); }
		}

		///<summary>
		/// ActionBarHeadline2
		///</summary>
		[ImplementPropertyType("actionBarHeadline2")]
		public string ActionBarHeadline2
		{
			get { return this.GetPropertyValue<string>("actionBarHeadline2"); }
		}

		///<summary>
		/// ActionBarHeadline3
		///</summary>
		[ImplementPropertyType("actionBarHeadline3")]
		public string ActionBarHeadline3
		{
			get { return this.GetPropertyValue<string>("actionBarHeadline3"); }
		}

		///<summary>
		/// ActionBarParagraph1
		///</summary>
		[ImplementPropertyType("actionBarParagraph1")]
		public string ActionBarParagraph1
		{
			get { return this.GetPropertyValue<string>("actionBarParagraph1"); }
		}

		///<summary>
		/// ActionBarParagraph2
		///</summary>
		[ImplementPropertyType("actionBarParagraph2")]
		public string ActionBarParagraph2
		{
			get { return this.GetPropertyValue<string>("actionBarParagraph2"); }
		}

		///<summary>
		/// ActionBarParagraph3
		///</summary>
		[ImplementPropertyType("actionBarParagraph3")]
		public string ActionBarParagraph3
		{
			get { return this.GetPropertyValue<string>("actionBarParagraph3"); }
		}
	}
}
