//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1075 with alias "baseContent"
	/// <summary>Base content</summary>
	public partial interface IBaseContent : IPublishedContent
	{
		/// <summary>Body text</summary>
		Newtonsoft.Json.Linq.JToken BodyText { get; }

		/// <summary>Headline</summary>
		string Headline { get; }

		/// <summary>Hero image</summary>
		IPublishedContent HeroImage { get; }

		/// <summary>Hero Image Headline</summary>
		string HeroImageHeadline { get; }
	}

	/// <summary>Base content</summary>
	[PublishedContentModel("baseContent")]
	public partial class BaseContent : PublishedContentModel, IBaseContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body text: Change text
		///</summary>
		[ImplementPropertyType("bodyText")]
		public Newtonsoft.Json.Linq.JToken BodyText
		{
			get { return GetBodyText(this); }
		}

		/// <summary>Static getter for Body text</summary>
		public static Newtonsoft.Json.Linq.JToken GetBodyText(IBaseContent that) { return that.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("bodyText"); }

		///<summary>
		/// Headline: Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return GetHeadline(this); }
		}

		/// <summary>Static getter for Headline</summary>
		public static string GetHeadline(IBaseContent that) { return that.GetPropertyValue<string>("headline"); }

		///<summary>
		/// Hero image: This is where you can change the image for the banner on each page
		///</summary>
		[ImplementPropertyType("heroImage")]
		public IPublishedContent HeroImage
		{
			get { return GetHeroImage(this); }
		}

		/// <summary>Static getter for Hero image</summary>
		public static IPublishedContent GetHeroImage(IBaseContent that) { return that.GetPropertyValue<IPublishedContent>("heroImage"); }

		///<summary>
		/// Hero Image Headline: Headline for image banner
		///</summary>
		[ImplementPropertyType("heroImageHeadline")]
		public string HeroImageHeadline
		{
			get { return GetHeroImageHeadline(this); }
		}

		/// <summary>Static getter for Hero Image Headline</summary>
		public static string GetHeroImageHeadline(IBaseContent that) { return that.GetPropertyValue<string>("heroImageHeadline"); }
	}
}
