//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Carousel images</summary>
	[PublishedContentModel("carouselImages")]
	public partial class CarouselImages : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselImages";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselImages(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselImages, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel image1
		///</summary>
		[ImplementPropertyType("carouselImage1")]
		public IPublishedContent CarouselImage1
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage1"); }
		}

		///<summary>
		/// Carousel image2
		///</summary>
		[ImplementPropertyType("carouselImage2")]
		public IPublishedContent CarouselImage2
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage2"); }
		}

		///<summary>
		/// Carousel image3
		///</summary>
		[ImplementPropertyType("carouselImage3")]
		public IPublishedContent CarouselImage3
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage3"); }
		}

		///<summary>
		/// Carousel image4
		///</summary>
		[ImplementPropertyType("carouselImage4")]
		public IPublishedContent CarouselImage4
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage4"); }
		}

		///<summary>
		/// Carousel image5
		///</summary>
		[ImplementPropertyType("carouselImage5")]
		public IPublishedContent CarouselImage5
		{
			get { return this.GetPropertyValue<IPublishedContent>("carouselImage5"); }
		}
	}
}
