//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1068 with alias "heroimgTallText"
	/// <summary>Heroimg-Tall+text</summary>
	public partial interface IHeroimgTallText : IPublishedContent
	{
		/// <summary>Heroimg</summary>
		IPublishedContent Heroimg { get; }

		/// <summary>Heroimg-Text</summary>
		string HeroimgText { get; }
	}

	/// <summary>Heroimg-Tall+text</summary>
	[PublishedContentModel("heroimgTallText")]
	public partial class HeroimgTallText : PublishedContentModel, IHeroimgTallText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "heroimgTallText";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeroimgTallText(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroimgTallText, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Heroimg
		///</summary>
		[ImplementPropertyType("heroimg")]
		public IPublishedContent Heroimg
		{
			get { return GetHeroimg(this); }
		}

		/// <summary>Static getter for Heroimg</summary>
		public static IPublishedContent GetHeroimg(IHeroimgTallText that) { return that.GetPropertyValue<IPublishedContent>("heroimg"); }

		///<summary>
		/// Heroimg-Text
		///</summary>
		[ImplementPropertyType("heroimgText")]
		public string HeroimgText
		{
			get { return GetHeroimgText(this); }
		}

		/// <summary>Static getter for Heroimg-Text</summary>
		public static string GetHeroimgText(IHeroimgTallText that) { return that.GetPropertyValue<string>("heroimgText"); }
	}
}
