//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Publikationer</summary>
	[PublishedContentModel("publikationer")]
	public partial class Publikationer : PublishedContentModel, IImageText
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "publikationer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Publikationer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Publikationer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// contentHeadline
		///</summary>
		[ImplementPropertyType("contentHeadline")]
		public string ContentHeadline
		{
			get { return this.GetPropertyValue<string>("contentHeadline"); }
		}

		///<summary>
		/// contentLeft
		///</summary>
		[ImplementPropertyType("contentLeft")]
		public string ContentLeft
		{
			get { return this.GetPropertyValue<string>("contentLeft"); }
		}

		///<summary>
		/// contentRight
		///</summary>
		[ImplementPropertyType("contentRight")]
		public string ContentRight
		{
			get { return this.GetPropertyValue<string>("contentRight"); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.ImageText.GetHeadline(this); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return Umbraco.Web.PublishedContentModels.ImageText.GetImage(this); }
		}
	}
}
