//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Shelter</summary>
	[PublishedContentModel("shelter")]
	public partial class Shelter : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "shelter";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Shelter(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Shelter, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("Address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("Address"); }
		}

		///<summary>
		/// CenterName
		///</summary>
		[ImplementPropertyType("centerName")]
		public string CenterName
		{
			get { return this.GetPropertyValue<string>("centerName"); }
		}

		///<summary>
		/// Center text
		///</summary>
		[ImplementPropertyType("centerText")]
		public IHtmlString CenterText
		{
			get { return this.GetPropertyValue<IHtmlString>("centerText"); }
		}

		///<summary>
		/// Mail
		///</summary>
		[ImplementPropertyType("mail")]
		public string Mail
		{
			get { return this.GetPropertyValue<string>("mail"); }
		}

		///<summary>
		/// PhoneNumber
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}
	}
}
