//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Activities</summary>
	[PublishedContentModel("activities")]
	public partial class Activities : PublishedContentModel, IBaseContent, IHeroHeader
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "activities";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Activities(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Activities, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hidden content
		///</summary>
		[ImplementPropertyType("hiddenContent")]
		public Newtonsoft.Json.Linq.JToken HiddenContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("hiddenContent"); }
		}

		///<summary>
		/// Popular activities list
		///</summary>
		[ImplementPropertyType("popularActivitiesList")]
		public IEnumerable<IPublishedContent> PopularActivitiesList
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("popularActivitiesList"); }
		}

		///<summary>
		/// Popular headline
		///</summary>
		[ImplementPropertyType("popularHeadline")]
		public string PopularHeadline
		{
			get { return this.GetPropertyValue<string>("popularHeadline"); }
		}

		///<summary>
		/// Shown content
		///</summary>
		[ImplementPropertyType("shownContent")]
		public Newtonsoft.Json.Linq.JToken ShownContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("shownContent"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return Umbraco.Web.PublishedContentModels.BaseContent.GetContent(this); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return Umbraco.Web.PublishedContentModels.BaseContent.GetHeadline(this); }
		}

		///<summary>
		/// HeroHeadline
		///</summary>
		[ImplementPropertyType("heroHeadline")]
		public string HeroHeadline
		{
			get { return Umbraco.Web.PublishedContentModels.HeroHeader.GetHeroHeadline(this); }
		}

		///<summary>
		/// HeroImage
		///</summary>
		[ImplementPropertyType("heroImage")]
		public IPublishedContent HeroImage
		{
			get { return Umbraco.Web.PublishedContentModels.HeroHeader.GetHeroImage(this); }
		}
	}
}
