//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Arbejder</summary>
	[PublishedContentModel("arbejder")]
	public partial class Arbejder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "arbejder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Arbejder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Arbejder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Arbejder afdeling
		///</summary>
		[ImplementPropertyType("arbejderAfdeling")]
		public string ArbejderAfdeling
		{
			get { return this.GetPropertyValue<string>("arbejderAfdeling"); }
		}

		///<summary>
		/// Arbejder billede
		///</summary>
		[ImplementPropertyType("arbejderBillede")]
		public IPublishedContent ArbejderBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("arbejderBillede"); }
		}

		///<summary>
		/// Arbejder e-mail
		///</summary>
		[ImplementPropertyType("arbejderEMail")]
		public string ArbejderEmail
		{
			get { return this.GetPropertyValue<string>("arbejderEMail"); }
		}

		///<summary>
		/// Arbejder navn
		///</summary>
		[ImplementPropertyType("arbejderNavn")]
		public string ArbejderNavn
		{
			get { return this.GetPropertyValue<string>("arbejderNavn"); }
		}

		///<summary>
		/// Arbejder telefon
		///</summary>
		[ImplementPropertyType("arbejderTelefon")]
		public int ArbejderTelefon
		{
			get { return this.GetPropertyValue<int>("arbejderTelefon"); }
		}
	}
}
