//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Arbejdsgiver</summary>
	[PublishedContentModel("employee")]
	public partial class Employee : PublishedContentModel, IPerson
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "employee";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Employee(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Employee, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Job title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return this.GetPropertyValue<string>("jobTitle"); }
		}

		///<summary>
		/// Profile image
		///</summary>
		[ImplementPropertyType("profileImage")]
		public IPublishedContent ProfileImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("profileImage"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("personEmail")]
		public string PersonEmail
		{
			get { return Umbraco.Web.PublishedContentModels.Person.GetPersonEmail(this); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("personName")]
		public string PersonName
		{
			get { return Umbraco.Web.PublishedContentModels.Person.GetPersonName(this); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("personPhone")]
		public string PersonPhone
		{
			get { return Umbraco.Web.PublishedContentModels.Person.GetPersonPhone(this); }
		}
	}
}
