//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Featured Item</summary>
	[PublishedContentModel("featuredItem")]
	public partial class FeaturedItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "featuredItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FeaturedItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeaturedItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Featured image
		///</summary>
		[ImplementPropertyType("featuredImage")]
		public IPublishedContent FeaturedImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("featuredImage"); }
		}

		///<summary>
		/// Featured link
		///</summary>
		[ImplementPropertyType("featuredLink")]
		public string FeaturedLink
		{
			get { return this.GetPropertyValue<string>("featuredLink"); }
		}

		///<summary>
		/// Featured Name
		///</summary>
		[ImplementPropertyType("featuredName")]
		public string FeaturedName
		{
			get { return this.GetPropertyValue<string>("featuredName"); }
		}
	}
}
