//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1173 with alias "featuredContent"
	/// <summary>featuredContent</summary>
	public partial interface IFeaturedContent : IPublishedContent
	{
		/// <summary>Headline</summary>
		string FeaturedHeadline { get; }

		/// <summary>List</summary>
		IEnumerable<IPublishedContent> FeaturedList { get; }
	}

	/// <summary>featuredContent</summary>
	[PublishedContentModel("featuredContent")]
	public partial class FeaturedContent : PublishedContentModel, IFeaturedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "featuredContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FeaturedContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeaturedContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("featuredHeadline")]
		public string FeaturedHeadline
		{
			get { return GetFeaturedHeadline(this); }
		}

		/// <summary>Static getter for Headline</summary>
		public static string GetFeaturedHeadline(IFeaturedContent that) { return that.GetPropertyValue<string>("featuredHeadline"); }

		///<summary>
		/// List
		///</summary>
		[ImplementPropertyType("featuredList")]
		public IEnumerable<IPublishedContent> FeaturedList
		{
			get { return GetFeaturedList(this); }
		}

		/// <summary>Static getter for List</summary>
		public static IEnumerable<IPublishedContent> GetFeaturedList(IFeaturedContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("featuredList"); }
	}
}
