//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Global Settings</summary>
	[PublishedContentModel("globalSettings")]
	public partial class GlobalSettings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "globalSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GlobalSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GlobalSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("organizationAddress")]
		public string OrganizationAddress
		{
			get { return this.GetPropertyValue<string>("organizationAddress"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("organizationCity")]
		public string OrganizationCity
		{
			get { return this.GetPropertyValue<string>("organizationCity"); }
		}

		///<summary>
		/// CVR-nummer
		///</summary>
		[ImplementPropertyType("organizationCVR")]
		public string OrganizationCvr
		{
			get { return this.GetPropertyValue<string>("organizationCVR"); }
		}

		///<summary>
		/// EAN-nummer
		///</summary>
		[ImplementPropertyType("organizationEAN")]
		public string OrganizationEan
		{
			get { return this.GetPropertyValue<string>("organizationEAN"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("organizationEmail")]
		public string OrganizationEmail
		{
			get { return this.GetPropertyValue<string>("organizationEmail"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("organizationLogo")]
		public IPublishedContent OrganizationLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("organizationLogo"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("organizationName")]
		public string OrganizationName
		{
			get { return this.GetPropertyValue<string>("organizationName"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("organizationPhone")]
		public string OrganizationPhone
		{
			get { return this.GetPropertyValue<string>("organizationPhone"); }
		}

		///<summary>
		/// Post code
		///</summary>
		[ImplementPropertyType("organizationPostCode")]
		public int OrganizationPostCode
		{
			get { return this.GetPropertyValue<int>("organizationPostCode"); }
		}
	}
}
