//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>good Story</summary>
	[PublishedContentModel("goodStory")]
	public partial class GoodStory : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "goodStory";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GoodStory(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GoodStory, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Age
		///</summary>
		[ImplementPropertyType("age")]
		public int Age
		{
			get { return this.GetPropertyValue<int>("age"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public string Link
		{
			get { return this.GetPropertyValue<string>("link"); }
		}

		///<summary>
		/// Quote
		///</summary>
		[ImplementPropertyType("quote")]
		public string Quote
		{
			get { return this.GetPropertyValue<string>("quote"); }
		}

		///<summary>
		/// Story description
		///</summary>
		[ImplementPropertyType("storyDescription")]
		public string StoryDescription
		{
			get { return this.GetPropertyValue<string>("storyDescription"); }
		}

		///<summary>
		/// Story image
		///</summary>
		[ImplementPropertyType("storyImage")]
		public IPublishedContent StoryImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("storyImage"); }
		}

		///<summary>
		/// Story Person Name
		///</summary>
		[ImplementPropertyType("storyName")]
		public string StoryName
		{
			get { return this.GetPropertyValue<string>("storyName"); }
		}
	}
}
