//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1159 with alias "location"
	/// <summary>location</summary>
	public partial interface ILocation : IPublishedContent
	{
		/// <summary>Address</summary>
		string Address { get; }

		/// <summary>City</summary>
		string City { get; }

		/// <summary>GPScoordinates</summary>
		string GPscoordinates { get; }

		/// <summary>PostCode</summary>
		int PostCode { get; }
	}

	/// <summary>location</summary>
	[PublishedContentModel("location")]
	public partial class Location : PublishedContentModel, ILocation
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "location";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Location(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Location, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return GetAddress(this); }
		}

		/// <summary>Static getter for Address</summary>
		public static string GetAddress(ILocation that) { return that.GetPropertyValue<string>("address"); }

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return GetCity(this); }
		}

		/// <summary>Static getter for City</summary>
		public static string GetCity(ILocation that) { return that.GetPropertyValue<string>("city"); }

		///<summary>
		/// GPScoordinates
		///</summary>
		[ImplementPropertyType("gPScoordinates")]
		public string GPscoordinates
		{
			get { return GetGPscoordinates(this); }
		}

		/// <summary>Static getter for GPScoordinates</summary>
		public static string GetGPscoordinates(ILocation that) { return that.GetPropertyValue<string>("gPScoordinates"); }

		///<summary>
		/// PostCode
		///</summary>
		[ImplementPropertyType("postCode")]
		public int PostCode
		{
			get { return GetPostCode(this); }
		}

		/// <summary>Static getter for PostCode</summary>
		public static int GetPostCode(ILocation that) { return that.GetPropertyValue<int>("postCode"); }
	}
}
