//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1290 with alias "scripts"
	/// <summary>scripts</summary>
	public partial interface IScripts : IPublishedContent
	{
		/// <summary>Footer</summary>
		IEnumerable<string> ScriptsFooter { get; }

		/// <summary>Header</summary>
		IEnumerable<string> ScriptsHeader { get; }
	}

	/// <summary>scripts</summary>
	[PublishedContentModel("scripts")]
	public partial class Scripts : PublishedContentModel, IScripts
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "scripts";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Scripts(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Scripts, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("scriptsFooter")]
		public IEnumerable<string> ScriptsFooter
		{
			get { return GetScriptsFooter(this); }
		}

		/// <summary>Static getter for Footer</summary>
		public static IEnumerable<string> GetScriptsFooter(IScripts that) { return that.GetPropertyValue<IEnumerable<string>>("scriptsFooter"); }

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("scriptsHeader")]
		public IEnumerable<string> ScriptsHeader
		{
			get { return GetScriptsHeader(this); }
		}

		/// <summary>Static getter for Header</summary>
		public static IEnumerable<string> GetScriptsHeader(IScripts that) { return that.GetPropertyValue<IEnumerable<string>>("scriptsHeader"); }
	}
}
