//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1181 with alias "seo"
	/// <summary>seo</summary>
	public partial interface ISeo : IPublishedContent
	{
		/// <summary>Meta description</summary>
		string MetaDescription { get; }

		/// <summary>Meta robots</summary>
		object MetaRobots { get; }
	}

	/// <summary>seo</summary>
	[PublishedContentModel("seo")]
	public partial class Seo : PublishedContentModel, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "seo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Seo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Seo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta description: Keep it within 160 characters, and write it to catch the user's attention. Sell the page.  Identical or similar descriptions on every page of a site aren't helpful for ranking.  (advice from Google)
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta description</summary>
		public static string GetMetaDescription(ISeo that) { return that.GetPropertyValue<string>("metaDescription"); }

		///<summary>
		/// Meta robots: Must be set to  INDEX,FOLLOW as a minimum.
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public object MetaRobots
		{
			get { return GetMetaRobots(this); }
		}

		/// <summary>Static getter for Meta robots</summary>
		public static object GetMetaRobots(ISeo that) { return that.GetPropertyValue("metaRobots"); }
	}
}
