//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1365 with alias "test"
	/// <summary>Underretning</summary>
	public partial interface ITest : IPublishedContent
	{
		/// <summary>description</summary>
		IEnumerable<IPublishedContent> DescriptionUnderretning { get; }

		/// <summary>headline</summary>
		IEnumerable<IPublishedContent> HeadlineUnderretning { get; }
	}

	/// <summary>Underretning</summary>
	[PublishedContentModel("test")]
	public partial class Test : PublishedContentModel, ITest
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "test";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Test(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Test, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// description
		///</summary>
		[ImplementPropertyType("descriptionUnderretning")]
		public IEnumerable<IPublishedContent> DescriptionUnderretning
		{
			get { return GetDescriptionUnderretning(this); }
		}

		/// <summary>Static getter for description</summary>
		public static IEnumerable<IPublishedContent> GetDescriptionUnderretning(ITest that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("descriptionUnderretning"); }

		///<summary>
		/// headline
		///</summary>
		[ImplementPropertyType("headlineUnderretning")]
		public IEnumerable<IPublishedContent> HeadlineUnderretning
		{
			get { return GetHeadlineUnderretning(this); }
		}

		/// <summary>Static getter for headline</summary>
		public static IEnumerable<IPublishedContent> GetHeadlineUnderretning(ITest that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("headlineUnderretning"); }
	}
}
